// <auto-generated />
namespace MvcApplication2.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _20191204 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20191204));
        
        string IMigrationMetadata.Id
        {
            get { return "201912040827042_20191204"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
