// <auto-generated />
namespace MvcApplication2.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _201912041702 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201912041702));
        
        string IMigrationMetadata.Id
        {
            get { return "201912040907482_201912041702"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
